### PR TITLE
Add cache to GraphQL queries

### PR DESCRIPTION
**Pull request by athoscouto**
#### What problem is this solving?

Too many requests could be cached.

#### How to test it?

Product page on `storecomponents`

https://athos--storecomponents.myvtex.com/everyday-necessaire/p

### CODE REVIEW

**Review by fabianaferreira — APPROVED** [review]
LGTM

**Comment by polishq** [comment]
@athoscouto Is there documentation for the various `@cacheControl` GraphQL options? Our team could benefit from a deeper understanding of the different scope and maxAge values.

**Review by wender — APPROVED** [review]

**Comment by athoscouto** [comment]
Hey @polishq! We have some info [here](https://github.com/vtex-apps/graphql-example#configuring-cache-for-specific-queries), but I'm not sure how up to date it is.

I know the logic around GraphQL is inside `graphql-server`, so I've searched there and [found this](https://github.com/vtex/graphql-server/blob/master/node/resources/maxAgeEnum.ts), which gives us information about how long each kind of cache lives.

Hope it helps. Maybe @vtex-apps/store-framework-devs can give more info.

**Comment by polishq** [comment]
> Hey @polishq! We have some info [here](https://github.com/vtex-apps/graphql-example#configuring-cache-for-specific-queries), but I'm not sure how up to date it is.
> 
> I know the logic around GraphQL is inside `graphql-server`, so I've searched there and [found this](https://github.com/vtex/graphql-server/blob/master/node/resources/maxAgeEnum.ts), which gives us information about how long each kind of cache lives.
> 
> Hope it helps. Maybe @vtex-apps/store-framework-devs can give more info.

Thanks! Very helpful. One more question: if no `@cacheControl` directive is set, does that mean there will be no caching on that query?

**Comment by athoscouto** [comment]
According to the first link I sent, yes. It may be outdated though.
I think the decision is based on the fact that we'd rather have no cache at all than cache things that we're not supposed to (e.g. private data).

**Comment by athoscouto** [comment]
@polishq I've deployed this PR with `2.x` and it does not work.
It seems that the cache logic is not implemented by GraphQL Server.
It is inside the node runtime.

The easy solution is to manually set the `Cache-Control` on response headers.

**Review by igorbrasileiro — APPROVED** [review]

**Comment by polishq** [comment]
@athoscouto We have removed the `@cacheControl` directives as part of https://github.com/vtex-apps/reviews-and-ratings/pull/112 . Given that as of 3.x reviews-and-ratings uses master data to store and retrieve reviews, is it acceptable to rely on MD's built-in caching? Or would you still recommend adding our own cache-control response headers?

**Comment by athoscouto** [comment]
Feel free to reopen if this is still needed.

**Pull request closed without merging**
