### PR TITLE
Use metric instead of logs to reduce log volume

### PR DESCRIPTION
**Pull request by athoscouto**
#### What problem is this solving?
Related to https://github.com/vtex-apps/reviews-and-ratings/issues/99.

#### How to test it?

`vtex link`
https://athos--storecomponents.myvtex.com/

### CODE REVIEW

**Review by fabianaferreira — APPROVED** [review]
LGTM

**Comment by fabianaferreira** [comment]
@athoscouto, LGTM. We just need to update the changelog accordingly (:

**Review by wender — APPROVED** [review]

**Review by polishq — CHANGES_REQUESTED** [review]
Rebase needed

**Comment by athoscouto** [comment]
Feel free to reopen if this is still needed.

**Pull request closed without merging**
